version: 0.0
os: linux

# Ensure all artifact files are copied to /root/gifmachine
files:
  - source: /
    destination: /root/gifmachine

hooks:
  ApplicationStart:
    - location: deploy-scripts/deploy.sh
      timeout: 300
      runas: root
